dist: trusty
language: node_js
node_js:
  - lts/*
branches:
  only:
    - gh-pages
cache:
  directories:
    - node_modules
env:
  global:
    - URL="http://w3c.github.io/pointerlock/ECHIDNA"
    - DECISION="https://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0627.html"

install:
  - npm install respec-validator
script:
  - npx respec-validator --gh-user=$GH_USER --gh-token=$GH_TOKEN index.html

after_success:
  - CC="mcaceres@mozilla.com"
  - echo "If it fails, check https://lists.w3.org/Archives/Public/public-tr-notifications/"
  - curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN" --data "cc=$CC"
